import { Navbar, Sidebar } from '@/components';
import './globals.css'

export const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

const RootLayout = ({ children }) => {
  return (
    <html lang="en">
      <body>
        <Navbar />
        <div className='flex'>
          <Sidebar />
          {children}
        </div>
      </body>
    </html>
  )
}

export default RootLayout;